"""
training_data.py — Dataset de treino para categorização.

🎓 POR QUE um dataset próprio?
Datasets públicos (Kaggle) são genéricos e em inglês. Pra um app BR,
precisamos de descrições reais brasileiras: iFood, Uber, Mercado Livre.

🎓 COMO o modelo aprende com isso?
Cada linha é um exemplo:
    ("iFood restaurante", "Alimentação")
    ("Uber viagem", "Transporte")
O modelo lê milhares dessas linhas e "aprende" que palavras como
"ifood", "restaurante", "lanche" indicam categoria Alimentação.

🎓 COMO expandir?
Adicione mais linhas aqui. Quanto mais dados, mais inteligente o modelo.
"""
from typing import List, Tuple

# Cada item: (descrição da transação, categoria correta)
DADOS_TREINO: List[Tuple[str, str]] = [
    # ===================== ALIMENTAÇÃO =====================
    ("iFood restaurante", "Alimentação"),
    ("ifood lanche", "Alimentação"),
    ("IFood delivery", "Alimentação"),
    ("restaurant Outback", "Alimentação"),
    ("restaurante cara", "Alimentação"),
    ("restaurante padaria", "Alimentação"),
    ("restaurante japonês", "Alimentação"),
    ("restaurante self service", "Alimentação"),
    ("padaria pao", "Alimentação"),
    ("padaria francesa", "Alimentação"),
    ("padaria do bairro", "Alimentação"),
    ("pizzaria domino's", "Alimentação"),
    ("pizza hut delivery", "Alimentação"),
    ("supermercado extra", "Alimentação"),
    ("supermercado pao de acucar", "Alimentação"),
    ("supermercado carrefour", "Alimentação"),
    ("mercado livre mercado", "Alimentação"),
    ("mercado da esquina", "Alimentação"),
    ("mercadinho", "Alimentação"),
    ("hortifruti frutas", "Alimentação"),
    ("hortifruti verduras", "Alimentação"),
    ("atacarejo atacadao", "Alimentação"),
    ("atacado distribuidora", "Alimentação"),
    ("acougue carne", "Alimentação"),
    ("acougue frango", "Alimentação"),
    ("mercearia compras", "Alimentação"),
    ("sacolao feira", "Alimentação"),
    ("cafeteria starbucks", "Alimentação"),
    ("cafe da manha", "Alimentação"),
    ("coffee shop", "Alimentação"),
    ("bar cerveja", "Alimentação"),
    ("boteco petisco", "Alimentação"),
    ("sorveteria", "Alimentação"),
    ("lanche mcdonalds", "Alimentação"),
    ("burguer king", "Alimentação"),
    ("subway lanche", "Alimentação"),
    ("habibs comida", "Alimentação"),
    ("giraffas prato", "Alimentação"),
    ("comida japonesa sushi", "Alimentação"),
    ("almoço self service", "Alimentação"),
    ("jantar restaurante", "Alimentação"),
    ("compras mercado", "Alimentação"),

    # ===================== TRANSPORTE =====================
    ("Uber viagem", "Transporte"),
    ("Uber app", "Transporte"),
    ("99 taxi", "Transporte"),
    ("99taxis corrida", "Transporte"),
    ("taxi prefeitura", "Transporte"),
    ("taxi aeroporto", "Transporte"),
    ("combustivel posto shell", "Transporte"),
    ("combustivel posto petrobras", "Transporte"),
    ("gasolina posto ipiranga", "Transporte"),
    ("alcool posto", "Transporte"),
    ("diesel posto", "Transporte"),
    ("gnv gas natural", "Transporte"),
    ("estacionamento shopping", "Transporte"),
    ("estacionamento aeroporto", "Transporte"),
    ("pedagio sem parar", "Transporte"),
    ("pedagio auto ban", "Transporte"),
    ("pedagio rodovia", "Transporte"),
    ("onibus municipal", "Transporte"),
    ("onibus intermunicipal", "Transporte"),
    ("metro bilhete unico", "Transporte"),
    ("metro sp", "Transporte"),
    ("bilhete unico", "Transporte"),
    ("passagem rodoviaria", "Transporte"),
    ("passagem onibus", "Transporte"),
    ("ipva detran", "Transporte"),
    ("licenciamento detran", "Transporte"),
    ("multa transito", "Transporte"),
    ("oficina mecanica carro", "Transporte"),
    ("manutencao veiculo", "Transporte"),
    ("troca de oleo", "Transporte"),
    ("alinhamento balanceamento", "Transporte"),
    ("lavagem carro", "Transporte"),

    # ===================== MORADIA =====================
    ("aluguel apartamento", "Moradia"),
    ("aluguel casa", "Moradia"),
    ("condominio", "Moradia"),
    ("taxa condominio", "Moradia"),
    ("conta de luz", "Moradia"),
    ("conta luz enemta", "Moradia"),
    ("enel energia eletrica", "Moradia"),
    ("cpfl energia", "Moradia"),
    ("conta de agua", "Moradia"),
    ("sabesp agua", "Moradia"),
    ("companhia agua esgoto", "Moradia"),
    ("gas encanado", "Moradia"),
    ("comgas gas", "Moradia"),
    ("gas natural encanado", "Moradia"),
    ("gas botijao", "Moradia"),
    ("liga gas", "Moradia"),
    ("internet vivo fibra", "Moradia"),
    ("internet net claro", "Moradia"),
    ("telefone fixo", "Moradia"),
    ("tv por assinatura", "Moradia"),
    ("net tv", "Moradia"),
    ("claro tv", "Moradia"),
    ("iptu prefeitura", "Moradia"),
    ("seguro residencial", "Moradia"),

    # ===================== SAÚDE =====================
    ("farmacia drogasil", "Saude"),
    ("farmacia pague menos", "Saude"),
    ("farmacia raia", "Saude"),
    ("farmacia sao paulo", "Saude"),
    ("drogaria remedio", "Saude"),
    ("medicamento compra", "Saude"),
    ("remedio dor", "Saude"),
    ("consulta medica", "Saude"),
    ("consulta medico", "Saude"),
    ("consulta cardiologista", "Saude"),
    ("consulta dentista", "Saude"),
    ("consulta oftalmologista", "Saude"),
    ("dentista implante", "Saude"),
    ("ortodontia aparelho", "Saude"),
    ("plano de saude", "Saude"),
    ("unimed mensalidade", "Saude"),
    ("sulamerica saude", "Saude"),
    ("bradesco saude", "Saude"),
    ("hospitalsanta casa", "Saude"),
    ("hospital sirio", "Saude"),
    ("exame laboratorial", "Saude"),
    ("laboratorio exames", "Saude"),
    ("exame sangue", "Saude"),
    ("laboratorio fleury", "Saude"),
    ("laboratorio dasa", "Saude"),
    ("academia smart fit", "Saude"),
    ("academia mensalidade", "Saude"),
    ("musculacao academia", "Saude"),
    ("fisioterapia", "Saude"),
    ("nutricionista consulta", "Saude"),

    # ===================== LAZER =====================
    ("cinemark ingresso", "Lazer"),
    ("cinema 3d", "Lazer"),
    ("ingresso theater", "Lazer"),
    ("show ingresso", "Lazer"),
    ("ingresso show musica", "Lazer"),
    ("spotify premium", "Lazer"),
    ("netflix mensalidade", "Lazer"),
    ("netflix assinatura", "Lazer"),
    ("disney plus", "Lazer"),
    ("hbo max", "Lazer"),
    ("prime video amazon", "Lazer"),
    ("youtube premium", "Lazer"),
    ("globoplay", "Lazer"),
    ("ingresso show rock", "Lazer"),
    ("parque diversao", "Lazer"),
    ("parque hopi hari", "Lazer"),
    ("playcenter ingresso", "Lazer"),
    ("biblioteca livro", "Lazer"),
    ("livraria cultura", "Lazer"),
    ("livraria saraiva", "Lazer"),
    ("amazon kindle", "Lazer"),
    ("steam jogo", "Lazer"),
    ("playstation store", "Lazer"),
    ("xbox game pass", "Lazer"),
    ("jogo pc download", "Lazer"),
    ("barzinho balada", "Lazer"),
    ("balada ingresso", "Lazer"),
    ("festa", "Lazer"),
    ("restaurante com show", "Lazer"),
    ("viagem passeio", "Lazer"),
    ("passeio turistico", "Lazer"),
    ("hotel hospedagem", "Lazer"),
    ("airbnb hospedagem", "Lazer"),
    ("booking hotel", "Lazer"),
    ("ingresso jogo futebol", "Lazer"),
    ("estadio futebol", "Lazer"),
    ("show anitta", "Lazer"),

    # ===================== COMPRAS =====================
    ("amazon compra", "Compras"),
    ("mercado livre produto", "Compras"),
    ("magalu magazine", "Compras"),
    ("magazine luiza", "Compras"),
    ("americanas produto", "Compras"),
    ("shopee compra", "Compras"),
    ("aliexpress china", "Compras"),
    ("shein roupa", "Compras"),
    ("renner roupas", "Compras"),
    ("ciac roupas", "Compras"),
    ("riachuelo roupas", "Compras"),
    ("c&A camisa", "Compras"),
    ("zara roupas", "Compras"),
    ("lojas marisa", "Compras"),
    ("cellular samsung", "Compras"),
    ("apple store iphone", "Compras"),
    ("samsung galaxy", "Compras"),
    ("xiaomi celular", "Compras"),
    ("casas bahia eletro", "Compras"),
    ("extra eletro", "Compras"),
    ("pontofrio geladeira", "Compras"),
    ("elettro ventilador", "Compras"),
    ("moveis madeira", "Compras"),
    ("mobly movel", "Compras"),
    ("ikea decoracao", "Compras"),
    ("tenis nike", "Compras"),
    ("adidas tenis", "Compras"),
    ("tenis esporte", "Compras"),
    ("cartao credito compra", "Compras"),
    ("fatura cartao", "Compras"),

    # ===================== SALÁRIO / RENDA =====================
    ("salario deposito", "Renda"),
    ("salario empresa", "Renda"),
    ("pagamento salario", "Renda"),
    ("salario liquido", "Renda"),
    ("adiantamento salario", "Renda"),
    ("decimo terceiro", "Renda"),
    ("ferias pagamento", "Renda"),
    ("freelance projeto", "Renda"),
    ("freela design", "Renda"),
    ("freela desenvolvimento", "Renda"),
    ("consultoria projeto", "Renda"),
    ("rendimento poupanca", "Renda"),
    ("rendimento tesouro", "Renda"),
    ("dividendo acoes", "Renda"),
    ("aluguel recebido", "Renda"),
    ("venda produto", "Renda"),
    ("venda usados", "Renda"),
    ("reembolso despesa", "Renda"),
    ("restituicao irpf", "Renda"),
    ("comissao venda", "Renda"),

    # ===================== EDUCAÇÃO =====================
    ("mensalidade faculdade", "Educação"),
    ("mensalidade escola", "Educação"),
    ("curso online udemy", "Educação"),
    ("curso alura", "Educação"),
    ("curso programacao", "Educação"),
    ("curso ingles", "Educação"),
    ("material escolar", "Educação"),
    ("livro didatico", "Educação"),
    ("matricula escola", "Educação"),
    ("anhanguera faculdade", "Educação"),
    ("usp mensalidade", "Educação"),
    ("estacio curso", "Educação"),
    ("estudo curso", "Educação"),
    ("xerox copia", "Educação"),
    ("livro universitario", "Educação"),
    ("pos graduacao", "Educação"),
    ("mba curso", "Educação"),

    # ===================== ASSINATURAS / SOFTWARE =====================
    ("assinatura adobe", "Assinaturas"),
    ("adobe creative cloud", "Assinaturas"),
    ("microsoft 365", "Assinaturas"),
    ("office 365", "Assinaturas"),
    ("github pro", "Assinaturas"),
    ("notion plus", "Assinaturas"),
    ("figma profissional", "Assinaturas"),
    ("chatgpt plus", "Assinaturas"),
    ("openai api", "Assinaturas"),
    ("aws amazon", "Assinaturas"),
    ("google workspace", "Assinaturas"),
    ("dropbox plus", "Assinaturas"),
    ("slack mensal", "Assinaturas"),
    ("zoom pro", "Assinaturas"),
    ("canva pro", "Assinaturas"),
    ("iCloud armazenamento", "Assinaturas"),
    ("google one", "Assinaturas"),
    ("linkedin premium", "Assinaturas"),

    # ===================== TRANSFERÊNCIAS =====================
    ("transferencia ted", "Transferencias"),
    ("transferencia doc", "Transferencias"),
    ("pix transferencia", "Transferencias"),
    ("pix enviado", "Transferencias"),
    ("pix recebido", "Transferencias"),
    ("transferencia banco", "Transferencias"),
    ("ted para outra conta", "Transferencias"),
    ("emprestimo parcela", "Transferencias"),
    ("financiamento parcela", "Transferencias"),
    ("consignado", "Transferencias"),
    ("saque caixa eletronico", "Transferencias"),
    ("deposito bancario", "Transferencias"),
    ("pagamento boleto", "Transferencias"),
    ("pagamento conta", "Transferencias"),
    ("pagamento conta de luz", "Transferencias"),
    ("boleto pago", "Transferencias"),
    ("darj imposto", "Transferencias"),
]

# Lista de categorias únicas (o modelo só pode prever uma destas)
CATEGORIAS_VALIDAS = sorted(set(cat for _, cat in DADOS_TREINO))
